### ISSUE TITLE
HS100 on-off button not working

### ISSUE THREAD

**Issue by ghost** [mozilla-iot/tplink-adapter#14]
The TP-Link HS100 works perfectly when switched on-off from the Gateway.
However, the switch button on the HS100 itself is not detected. When switched on or off from the HS100, the Gateway doesn't detect the new state of the plug.

Is it a known behavior or a bug?

**Comment by mrstegeman** [comment]
The state of the plug is polled every 5 seconds. If you wait 5-10 seconds after clicking the button, do you see the UI update?
