### ISSUE TITLE
colorTemperature not working

### ISSUE THREAD

**Issue by TommySchwartz** [mozilla-iot/tplink-adapter#17]
Bought a Tp-link LB120 today. Everything works except for colorTemperature. Mozilla gateway can read the value but not set it. Also when I try to set it from Mozilla gateway the specific device hangs a good 5 minutes before starting to respond, it then execute the queue you have built up clicking during the freeze. 

Raspberry pi 3B+
Mozilla Gateway 0.6.1 (from img file)
Tp-link LB120: HW 1.0, FW 1.2.3

The bulb works fine within Kasa.

Best regards
Tommy

**Comment by mrstegeman** [comment]
I can confirm this with my LB120. I’ll take a look as soon as I get a chance.

**Comment by TommySchwartz** [comment]
Good my first post on github was of use :)
Looks like it was an easy fix, just changing names. However I can't seem to test it as I don't know how to install properly, and mozilla gateway just overwrites the files I try to replace. I'll just wait, at least I know there is a fix in the future. Thank you 👍

**Comment by mrstegeman** [comment]
@TommySchwartz I've merged the new add-on. Let me know if you still have issues after your add-on updates to v0.3.3.

**Comment by TommySchwartz** [comment]
Working perfectly, thank you! :)
