### ISSUE TITLE
HS100 icon showing as on/off switch

### ISSUE THREAD

**Issue by clockbrain** [mozilla-iot/tplink-adapter#21]
I have both a HS100 and HS110. Both work as expected however the HS100 icon shows as an on/off switch while the HS110 icon shows as a smart plug.

I guess maybe its because here [https://github.com/mozilla-iot/tplink-adapter/blob/76d3aa47d5dc1df59a83f2b405d109fd2a781a02/pkg/tplink_device.py#L109](https://github.com/mozilla-iot/tplink-adapter/blob/76d3aa47d5dc1df59a83f2b405d109fd2a781a02/pkg/tplink_device.py#L109) it only sets the type as a switch and not also 'SmartPlug' but I don't know what any other implications there would be to adding that type. 

Not a huge issue but it does make it slightly harder to find the right device amongst many on the things page.

**Comment by mrstegeman** [comment]
Historically, our  `SmartPlug` type required power/energy properties, but that is no longer the case. I'll add the `SmartPlug` type where appropriate. Thanks for letting me know!
