### ISSUE TITLE
HS100 frequently appears as disconnected

### ISSUE THREAD

**Issue by pascalin** [mozilla-iot/tplink-adapter#26]
Hi,

I configured my gateway and I'm using it to control an HS100 smart plug. However, since a couple of days ago, it frequently appears as disconnected even when it is on and I can control it using TP-Link's app. If I disable/enable the TP-Link it works again.
[tplink.log](https://github.com/mozilla-iot/tplink-adapter/files/3254733/tplink.log)

Thanks!

**Comment by mrstegeman** [comment]
That's very strange. I've never seen this happen in my ~2 years of using and developing this add-on with numerous devices.

Is your smart plug on the latest firmware?

**Comment by pascalin** [comment]
Yes, it is updated, but the problem was fixed by configuring the plug by its IP address. Indeed, my raspberry's hw or sw was seemingly failing and now it is not working anymore. I will confirm if this is still happening once I configure it again.
