### ISSUE TITLE
tp-link hs105 if added then deleted, can't be re-added.

### ISSUE THREAD

**Issue by montyrwalls** [mozilla-iot/tplink-adapter#29]
I have a hs105 I use for Christmas lights.  At the end of the season I deleted it after removing it from Christmas rules.  I removed it from the tp-link adapter configureation also.  Now I've added back in to the tp-link adapter configuration and it isn't visible now.  I can add new tp-link hs105s, but the previously deleted one doesn't show up.

**Comment by mrstegeman** [comment]
Since you said you "removed it from the adapter configuration", does that mean you had your devices manually configured by IP address in the gateway? If so, is it possible that your device now has a different IP address?

**Comment by montyrwalls** [comment]
When I initially configure an iot device, I assign a permanent ip address on a dedicated restricted vlan.  So it's on the original ip address (permanent dhcp reservation of the ip address).

**Comment by mrstegeman** [comment]
Should be fixed in v0.5.1, which I just released.

**Comment by montyrwalls** [comment]
cool.  Thank you.
