### ISSUE TITLE
ImportError: No module named 'gateway_addon'

### ISSUE THREAD

**Issue by joelthe1** [mozilla-iot/tplink-adapter#5]
I was following the [blog post](https://hacks.mozilla.org/2018/02/how-to-build-your-own-private-smart-home-with-a-raspberry-pi-and-mozillas-things-gateway/) trying to connect a tp-link HS100 smart Wi-Fi plug. For doing that I tried installing an add-on from the interface, however in the logs, I see this error:
```
File "/myhomepath/gateway/build/addons/tplink-adapter/main.py", line 5, in <module>
     Import gateway_addon
ImportError: No module named 'gateway_addon'
tplink-adapter died, code = 1 restarting...
```
Over and over again.

I'm using the latest stable version of the gateway code. The tp-link add-on version is 0.1.0
Any pointers would be appreciated.

**Comment by mrstegeman** [comment]
If you're running this outside of the Raspberry Pi gateway image (which it appears you are), you'll need to manually install that Python module as such: `sudo pip3 install git+https://github.com/mozilla-iot/gateway-addon-python.git`

**Comment by joelthe1** [comment]
Thanks @mrstegeman for that information.
For the benefit of others here are the dependencies I needed to install to get it to work in RP3:

- [CMake](https://cmake.org/download/)
- [nanomsg](https://github.com/nanomsg/nanomsg)
and then
- sudo pip3 install git+https://github.com/mozilla-iot/gateway-addon-python.git
